service: desafio-arcca
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
  hello:
    handler: function.hello
    events:
      - schedule: rate(1 hour)
