service: desafio-arcca
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 50

plugins:
  - serverless-offline
  - serverless-plugin-typescript

configValidationMode: error

functions:
  api:
    handler: src/functions/api/server.handler
    events:
      - httpApi:
          path: /
          method: POST

  cronjob:
    handler: src/functions/job/job.handler
    events:
      - schedule: rate(5 minutes)
